
project_id = "jhlawjmyorpmafokxtuh"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://auth.biblenow.io"
additional_redirect_urls = [
  "https://studio.biblenow.io/dashboard",
  "https://studio.biblenow.io/home",
  "http://localhost:4173"
]
                            
cookie_options.domain = "biblenow.io"
cookie_options.same_site = "lax"
cookie_options.secure = true
    
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = true
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[functions]
serve_local_supabase = true

[functions.link-firebase-user]
verify_jwt = false

